version: "2.0"
services:
  node:
    image: node:4.0.0-slim
    volumes:
      - .:/app
    working_dir: /app
    command: npm install
    environment:
      PGHOST: postgres-server
      PGUSER: zabbix
      PGPASSWORD: zabbix
    links:
      - postgres-server
      - zabbix-web
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-3.0.14
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_POSTMAXSIZE: 64M
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:80
    
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-3.0.14
    privileged: true

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-3.0.14
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
      - zabbix-agent    

  postgres-server:
    image: postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix


# d up -d postgres-server && sleep 2 && d up -d zabbix-server && sleep 2 && d up -d